### ISSUE TITLE
Error: can't open file 'PYKE/execute.py'

### ISSUE THREAD

**Issue by ghost** [dice-group/Vectograph#1]
I got this error:  `can't open file 'PYKE/execute.py'` when running **example_pyke.py** into my local machine. I guess due to file_paths, but I can't locate file execute.py in Vectorgraph.

**Comment by Demirrr** [comment]
Please be sure that you are currently using development branch. Readme file is updated to make the installation more explicit.

**Comment by ghost** [comment]
Thanks, the code works fine and generated the embedding. However, it throughs another error in "Type Prediction" step: 
```
###### Type Prediction  starts ######
Traceback (most recent call last):
  File "PYKE/execute.py", line 80, in <module>
    analyser.perform_type_prediction(learned_embeddings)
  File "/home/hzahera/Documents/SVN/DAIKIRI/Vectograph/PYKE/helper_classes.py", line 29, in debug
    r = func(*args, **kwargs)
  File "/home/hzahera/Documents/SVN/DAIKIRI/Vectograph/PYKE/helper_classes.py", line 548, in perform_type_prediction
    all_types = sorted(set.union(*list(type_info.values())))
TypeError: descriptor 'union' of 'set' object needs an argument
1708.1006073951721
```

Any hint?

**Comment by Demirrr** [comment]
Given that you follow the instructions as shown in the Readme. The following executions do not cause any exception.

`python main.py --model Pyke`

`python main.py --model Distmult`
