### ISSUE TITLE
Using Vectograph in deployment

### ISSUE THREAD

**Issue by hzahera** [dice-group/Vectograph#11]
I have used vectograph library in  one of my application to create a RDF graph. I find some errors during the deployment due to unused imports e.g. `import torch in transformers.py` 
https://github.com/dice-group/vectograph/blob/e7d53cdb04403890884a95051708b6b781506e01/vectograph/transformers.py#L6

Can we have a version of Vectograph with only used imports in each file?

Thanks,

**Comment by Demirrr** [comment]
Dear @hzahera 

As you can see in the setup python script (https://github.com/dice-group/vectograph/blob/e7d53cdb04403890884a95051708b6b781506e01/setup.py#L13), torch is one of the required third party libraries. So if you have followed, I would not expect any import related errors:
```
git clone https://github.com/dice-group/Vectograph.git
conda create -n temp python=3.6 # Or be sure that your have Python => 3.6.
conda activate temp
pip install -e . 
python -c "import vectograph"
python -m pytest tests
```
