### ISSUE TITLE
remove Event_ from generated RDF triples?

### ISSUE THREAD

**Issue by hzahera** [dice-group/Vectograph#13]
I am using hectograph for Lymphograph dataset (medical data), I think no need to add  'Event_' to generated RDF triples, I saved only original IDs only. What do you think?

https://github.com/dice-group/vectograph/blob/20bb5e92f4685589ffbf2dde06d0db269b30c8f6/vectograph/transformers.py#L71

https://github.com/dice-group/vectograph/blob/20bb5e92f4685589ffbf2dde06d0db269b30c8f6/main.py#L39

**Comment by Demirrr** [comment]
@hzahera you can very well remove the **Event_ prefix**. Yet, this prefix is used to denote the fact that the i.th row in a tabular data corresponds to [the CBD](https://www.w3.org/Submission/CBD/#:~:text=Given%20a%20particular%20node%20in,denoted%20by%20that%20particular%20node.) of i.th event in our current conversion schema. Hence, here, we are distinguishing between entities/nodes in a knowlege graph, namely, head entities are events and tail entities are discretized values in an input KG.
