### ISSUE TITLE
Documentation of Interfaces: ClusterPurity and TypePrediction

### ISSUE THREAD

**Issue by heindorf** [dice-group/Vectograph#8]
The key interfaces should be documented (at least the input and output parameters), particularly:
- `ClusterPurity`
- `TypePrediction`

**Comment by Demirrr** [comment]
Agreed. I am working on it. Today or at least by the end of the tomorrow,

- The each bit of code will be documented. 
- Mappings that are generated by Quantile-based discretization function will be stored. This implies that one can easily figure out which a numerical value denoted by` box_number_in_site` column belong to which bin. Please consider the following example:

Assume we have original column name: `box_number_in_site`
we include base_iri: `https://ai4bd.com/resource/box_number_in_site`
Original values: `[38.0,  34.0, ....., 136.0]`
discrited values: `['https://ai4bd.com/resource/box_number_in_site_quantile_1', 'https://ai4bd.com/resource/box_number_in_site_quantile_0', ...., https://ai4bd.com/resource/box_number_in_site_quantile_7]
`

**Comment by Demirrr** [comment]
Done. Please pull the changes.
