### ISSUE TITLE
Change the filename!

### ISSUE THREAD

**Issue by ghost** [dice-group/Vectograph#9]
df_embeddings = pd.read_csv(self.params['storage_path'] + '/PYKE_50_embd.csv', index_col=0)

'/PYKE_50_embd.csv' should be a variable file name, not fixed with 50 dim embeddings. 

https://github.com/dice-group/Vectograph/blob/f6ce809aabb5f1079142495570dd9e51dbda56fe/vectograph/transformers.py#L416

**Comment by Demirrr** [comment]
Thank you for pointing out @hamadazahera, you are right. The error is fixed.
